### ISSUE TITLE
Dimelo gcm device registration on UIThread

### ISSUE THREAD

**Issue by pedrocactus** [dimelo/Dimelo-Android#15]
Hello,

Not an issue, but not documented behavior neither pertinent for the client.
Registering using `Dimelo.setDeviceToken()` in background thread throws an exception.

Cheers

**Comment by Cylix** [comment]
Hi,

I tried to reproduce the issue but could not achieve it.
I modified our sample app by moving this [line](https://github.com/dimelo/Dimelo-Android-SampleApp/blob/master/app/src/main/java/com/dimelo/sampleapp/MainActivity.java#L120) into the doInBackground function and it worked fine.

Do you have any backtrace or code sample that produces the error.

Best

**Comment by pedrocactus** [comment]
`java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
                                                                       at android.os.Handler.<init>(Handler.java:200)
                                                                       at android.os.Handler.<init>(Handler.java:114)
                                                                       at com.dimelo.dimelosdk.utilities.DimeloTaskDelayer.<init>(DimeloTaskDelayer.java:20)
                                                                       at com.dimelo.dimelosdk.main.DimeloConnection.sendRequestWithDelay(DimeloConnection.java:271)
                                                                       at com.dimelo.dimelosdk.main.DimeloConnection.registerApp(DimeloConnection.java:434)
                                                                       at com.dimelo.dimelosdk.main.Dimelo.registerIfNeeded(Dimelo.java:997)
                                                                       at com.dimelo.dimelosdk.main.Dimelo.registerIfNeeded(Dimelo.java:938)
                                                                       at com.dimelo.dimelosdk.main.Dimelo.setDeviceToken(Dimelo.java:536)`

**Comment by Cylix** [comment]
This issue has been fixed in v1.5.0.

Basically, the problem was coming because we use internally use Handlers to dispatch network request.
This requires having a looping thread which was not your case.

We decided to implement a fallback to the MainLooper in the case where the thread is not a a looping one.
