### ISSUE TITLE
ConnectionChangeReceiver crash

### ISSUE THREAD

**Issue by SaschaMaekler** [dimelo/Dimelo-Android#3]
Hey,

Your com.dimelo.dimelosdk.main.ConnectionChangeReceiver crashes if the state of the network is changed and Dimelo isn't initialized at start of the Application.

`java.lang.RuntimeException: Unable to start receiver com.dimelo.dimelosdk.main.ConnectionChangeReceiver: java.lang.IllegalStateException: "Dimelo.getInstance()" cannot be called before "Dimelo.setup()" (Dimelo must be initialized)
                                                                         at android.app.ActivityThread.handleReceiver(ActivityThread.java:3000)
                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:177)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1525)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:145)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5942)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at java.lang.reflect.Method.invoke(Method.java:372)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                                      Caused by: java.lang.IllegalStateException: "Dimelo.getInstance()" cannot be called before "Dimelo.setup()" (Dimelo must be initialized)
                                                                         at com.dimelo.dimelosdk.main.Dimelo.getInstance(Dimelo.java:273)
                                                                         at com.dimelo.dimelosdk.helpers.DimeLog.d(DimeLog.java:17)
                                                                         at com.dimelo.dimelosdk.helpers.DimeLog.d(DimeLog.java:13)
                                                                         at com.dimelo.dimelosdk.main.ConnectionChangeReceiver.onReceive(ConnectionChangeReceiver.java:27)
                                                                         at android.app.ActivityThread.handleReceiver(ActivityThread.java:2993)
                                                                         at android.app.ActivityThread.access$1800(ActivityThread.java:177) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1525) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:145) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:5942) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) `

Greetings

**Comment by elhu** [comment]
Hi @SaschaMaekler ,

First of all, thanks for the report.
Could you please let me know which version of the SDK you're using?

Thanks!

**Comment by SaschaMaekler** [comment]
I'm using v1.2.2.1

**Comment by elhu** [comment]
Thanks for the clarification.
I believe I have reproduced the issue, we should be able to release a fix soon hopefully.

**Comment by SaschaMaekler** [comment]
Thank you for the fast response 👍

**Comment by elhu** [comment]
@SaschaMaekler I have pushed a new version (1.2.2.2) on the `dev-1.2.2.2` branch.
This resolves the situation in my case, could you please try it out on your side and confirm if the fix is working for you as well?

If so, I should be able to release pretty soon.

**Comment by SaschaMaekler** [comment]
@elhu looks good to me. No more crashes. 
Thank you very much

**Comment by elhu** [comment]
Hi @SaschaMaekler !

I've officially release version 1.2.2.2, including the fix for this issue and a couple others.
