### ISSUE TITLE
Crash when clicking on camera

### ISSUE THREAD

**Issue by RobertAndale** [dimelo/Dimelo-Android#52]
Hi, we detected a crash  (Galaxy Note 9 Android 8.1) or a black screen (Pixel 3 android 10, Samsung Galaxy S9 android 10, Pixel 2 XL android 10) when clicking on camera icon to send a picture.
It works fine on Samsung Galaxy S6 android 6.0.1 et Samsung Galaxy S3 4.4.4.

Is there any known issue in 1.9 SDK ?

**Comment by waelba** [comment]
Hi @RobertAndale ,

Could you please share your application logs when you click the camera icon ?

Best regards,

**Comment by RobertAndale** [comment]
@wa-el here are the logs : 

2020-06-26 08:26:36.465 2521-2521/com.orange.myorange.oxx W/System.err: java.io.IOException: Permission denied
2020-06-26 08:26:36.465 2521-2521/com.orange.myorange.oxx W/System.err:     at java.io.UnixFileSystem.createFileExclusively0(Native Method)
2020-06-26 08:26:36.465 2521-2521/com.orange.myorange.oxx W/System.err:     at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
2020-06-26 08:26:36.465 2521-2521/com.orange.myorange.oxx W/System.err:     at java.io.File.createTempFile(File.java:2018)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at com.dimelo.dimelosdk.utilities.CameraIntentHelper.createImageFile(CameraIntentHelper.java:33)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at com.dimelo.dimelosdk.utilities.CameraIntentHelper.dispatchTakePictureAndSaveIntent(CameraIntentHelper.java:78)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at com.dimelo.dimelosdk.main.StartAndValidateAttachmentProvider.startCamera(StartAndValidateAttachmentProvider.java:230)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at com.dimelo.dimelosdk.main.StartAndValidateAttachmentProvider.onCreate(StartAndValidateAttachmentProvider.java:95)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.Activity.performCreate(Activity.java:7825)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.Activity.performCreate(Activity.java:7814)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.os.Looper.loop(Looper.java:214)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7356)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-06-26 08:26:36.466 2521-2521/com.orange.myorange.oxx W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by RobertAndale** [comment]
@wa-el did the log help ?

**Comment by waelba** [comment]
@RobertAndale do you still have the bug ?

**Comment by RobertAndale** [comment]
@wa-el Yes we still have the bug using sdk 1.9.+ or even 2.0.+
When I click on the camera icon to take a picture, it still displays a black screen (Pixel 2 XL android 11)

**Comment by DrissTM** [comment]
@RobertAndale I'm closing this issue as it's quite old, please don't hesitate to re-open if you still need assistance on this
