### ISSUE TITLE
App Crashing when setting userIdenifier

### ISSUE THREAD

**Issue by OoredooMobile** [dimelo/Dimelo-Android#9]
i'm getting the below log when i try to use `setUserIdentifier`

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                         at com.dimelo.dimelosdk.Models.SourceInfo.updateWelcomeMessage(SourceInfo.java:50)
                                                                         at com.dimelo.dimelosdk.Models.SourceInfo.updateFromJson(SourceInfo.java:27)
                                                                         at com.dimelo.dimelosdk.main.DimeloConnection.consumeSourceInfo(DimeloConnection.java:455)
                                                                         at com.dimelo.dimelosdk.main.DimeloConnection.consumeResponse(DimeloConnection.java:439)
                                                                         at com.dimelo.dimelosdk.main.DimeloConnection.access$800(DimeloConnection.java:44)
                                                                         at com.dimelo.dimelosdk.main.DimeloConnection$6.onResponse(DimeloConnection.java:411)
                                                                         at com.dimelo.dimelosdk.main.DimeloConnection$6.onResponse(DimeloConnection.java:406)
                                                                         at com.dimelo.dimelosdk.helpers.requests.JsonDimeloRequest.deliverResponse(JsonDimeloRequest.java:43)
                                                                         at com.dimelo.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by Cylix** [comment]
Hi,

Thanks for reporting the issue.
Can you confirm me which version of the SDK you are currently using? Seems like you are using v1.4.0, but I want to make sure.

If you are not using the latest version (1.4.1), can you try to check if that v1.4.1 fixes your issue?
This minor release fixed some small issues related to the welcome message feature, technically including this issue.

Best

**Comment by OoredooMobile** [comment]
yes correct, I'm using v 1.4.0, i did not change to v 1.4.1 because you have not yet make a release, in release section. i changed it to v 1.4.1 and it's fixed now.

Thank you a lot

**Comment by Cylix** [comment]
Thanks for notifying us about that: I just updated the release section!
